


export const headerPresets = [
{
title: "Header",
backgroundColor:"#697268",
color:"#E2E8DD",
borderWidth: false,
borderColor:"#697268",
fontWeight: false,
textShadow: true,
},
{
title: "Header",    
backgroundColor: "#379683",
color: "#8EE4AF",    
borderWidth: false,
borderColor: "#379683",
fontWeight: true,
textShadow: true, 
},
{
title: "Header",    
backgroundColor: "#f3d250",
color: "#ececec",
borderWidth: false,
borderColor:"#f3d250",
fontWeight: true,
textShadow: false, 
},
{
title: "Header",
backgroundColor:    "magenta",
color:    "",   
borderWidth:  false,   
borderColor:    "magenta",
fontWeight: true,
textShadow:  false, 
},
{
title: "Header",
backgroundColor: "Chocolate",
color: "beige",
borderWidth: false,
borderColor: "Chocolate",
fontWeight: true,
textShadow: true,
},
{
title: "Header",
backgroundColor: "#e3e2df",
color: "#EE4C7c",
borderWidth: false,
borderColor: "#e3e2df",
fontWeight: true,
textShadow: false,
},
{
title: "Header",
backgroundColor: "#050747",
color: "gold",
borderWidth: false,
borderColor: "#050747",
fontWeight: false,
textShadow: true,
},
{
title: "Header",
backgroundColor:"#FFe5d9",
color:"white",
borderWidth: false,
borderColor:"#FFe5d9",
fontWeight: true,
textShadow: true,
}
]

export const backgroundPresets = [
{
    title: "Background",
    backgroundColor:"#4E5340",
},
{
    title: "Background",
    backgroundColor: "#5CDb95",
},
{
    title: "Background",
    backgroundColor: "#5DA2d5",
},
{
    title: "Background",
    backgroundColor: "black",
},
{
    title: "Background",
    backgroundColor: "BurlyWood",
},
{
    title: "Background",
    backgroundColor: "#e3e2df",
},
{
    title: "Background",
    backgroundColor: "#050747",
},
{
    title: "Background",
    backgroundColor: "#FFe5d9",
}
]

export const bodyPresets = [    
{
title: "Main Body",
backgroundColor:"#697268",
color:"white",
borderWidth: true,
borderColor:"#E2E8DD",
fontWeight: false,
textShadow: true,
boxShadow: false,
borderRadius: false,
},
{
title: "Main Body",
backgroundColor: "navy",
color: "rgb(255, 255, 255)",    
borderWidth:    false,
borderColor: "#8EE4AF",
fontWeight:    false,
textShadow:    true,
boxShadow:    false,
borderRadius:    false,
},
{
title: "Main Body",
backgroundColor:        "#90ccf4", 
color:        "white",
borderWidth:        true,
borderColor:        "#ececec",
fontWeight:        false,
textShadow:        false,
boxShadow:        true,
borderRadius:        true,
},
{
title: "Main Body",
backgroundColor: "black",
color: "white",
borderWidth: true,
borderColor: "#38F21E",
fontWeight: false,
textShadow: false,
boxShadow: false,
borderRadius: false,
},
{
title: "Main Body",
backgroundColor: "beige",
color: "",
borderWidth: true,
borderColor: "saddlebrown",
fontWeight: false,
textShadow: false,
boxShadow: true,
borderRadius: false,
},
{
title: "Main Body",
backgroundColor: "#e3e2df",
color: "#5d001e",
borderWidth: true,
borderColor: "#EE4C7c",
fontWeight: false,
textShadow: false,
boxShadow: false,
borderRadius: false,
},
{
title: "Main Body",
backgroundColor: "#050747",
color:        "white",    
borderWidth:        false,  
borderColor:        "gold",  
fontWeight:        false,   
textShadow:        false,   
boxShadow:        false,  
borderRadius:        false,   
},
{
title: "Main Body",
backgroundColor:"#f4acb7",
color:"white",
borderWidth:true,
borderColor:"white",
fontWeight:false,
textShadow:false,
boxShadow:false,
borderRadius: true,
}
]

export const buttonPresets = [
{    
title: "Button",
backgroundColor:"#5E6D6E",
color:"white",
borderWidth: true,
borderColor:"#E2E8DD",
fontWeight: true,
textShadow:true,
boxShadow:true,
borderRadius:true,
}, 
{
title: "Button",
backgroundColor:    "#8EE4AF",
color:    "navy",
borderWidth: false,
borderColor:    "rgb(255, 255, 255)",
fontWeight:    true,
textShadow:    false,
boxShadow:    true,
borderRadius:    true,
},
{
title: "Button",
backgroundColor:"orange",
color:"white",        
borderWidth:true,
borderColor:"white",
fontWeight:true,
textShadow:false,        
boxShadow:true,
borderRadius:true,
},
{
title: "Button",
backgroundColor:"black",
color:"white",  
borderWidth:true,
borderColor:"magenta",
fontWeight:true,
textShadow:false,   
boxShadow:true,
borderRadius:false, 
},
{
title: "Button",
backgroundColor: "Chocolate", 
color: "beige",
borderWidth: true,
borderColor: "saddlebrown",
fontWeight: true,
textShadow: false,
boxShadow: true,
borderRadius: true,
},
{
title: "Button",
backgroundColor:"#e3afbc",
color:"#5d001e",
borderWidth: true,
borderColor:"#EE4C7c",
fontWeight: true,
textShadow:false,
boxShadow:false,
borderRadius: false,
},
{
title: "Button",
backgroundColor: "#178582",
color: "white",
borderWidth: false,
borderColor: "#050747",
fontWeight: true,
textShadow: false,
boxShadow: true,
borderRadius: true,
},
{
title: "Button",
backgroundColor: "#F494BE",
color:"white",
borderWidth: false,
borderColor:"black",
fontWeight: false,
textShadow: false,
boxShadow: true,
borderRadius: true,
}
]

export const sidebarPresets = [
{
title: "Sidebar",
backgroundColor: "#95A3A4",
color:"white",
borderWidth: false,
borderColor:"#95A3A4",
fontWeight: true,
textShadow:true,
}, 
{
title: "Sidebar",
backgroundColor:"navy",
color:"#379683",
borderWidth: false,
borderColor:"",
fontWeight:true,
textShadow:true,

},
{
title: "Sidebar",
backgroundColor:"#ececec",   
color:"#5DA2d5",    
borderWidth: false,    
borderColor:"",    
fontWeight:true,   
textShadow: false,   
},
{
title: "Sidebar",
backgroundColor:"#38F21E",
color:"black",
borderWidth: false,
borderColor:"",
fontWeight:true,
textShadow:false,
},
{
title: "Sidebar",
backgroundColor:"beige",
color:"saddlebrown",
borderWidth: false,
borderColor:"saddlebrown",
fontWeight:true,
textShadow: false,
},
{
title: "Sidebar",
backgroundColor: "#e3e2df",
color:"#EE4C7c",
borderWidth: false,
borderColor:"#e3e2df",
fontWeight: false,
textShadow: false,
},
{
title: "Sidebar",
backgroundColor:"#050747",
color:"gold",
borderWidth: false,
borderColor:"",
fontWeight: true,
textShadow: false,
},
{
title: "Sidebar",
backgroundColor: "#d8e2dc",
color: "",
borderWidth: false,
borderColor:"#d8e2dc",
fontWeight: true,
textShadow: false,
}
]

export const footerPresets = [
{
title: "Footer",
backgroundColor: "#697268",
color: "#E2E8DD",
borderWidth: false,
borderColor: "#697268",
fontWeight: true,
textShadow: true,
},
{
title: "Footer",
backgroundColor:"#379683",   
color:"#8EE4AF",   
borderWidth: false,   
borderColor:"#379683",
fontWeight: true,
textShadow: true,
},
{
title: "Footer",
backgroundColor:"#F78888",
color:"white", 
borderWidth: false, 
borderColor:"#F78888",
fontWeight:false,
textShadow:false,
},
{
title: "Footer",
backgroundColor:"magenta",
color: "black",
borderWidth: false,
borderColor:"magenta",
fontWeight: true,
textShadow:false,
},
{
title: "Footer",
backgroundColor:"Chocolate",
color:"beige",
borderWidth:false,
borderColor:"Chocolate",
fontWeight: true,
textShadow:false,
},
{
title: "Footer",
backgroundColor:"#e3e2df",
color:"#5d001e",
borderWidth: true,
borderColor:"#e3e2df",
fontWeight:false,
textShadow:false,
},
{
title: "Footer",
backgroundColor:"#050747",
color:"white",
borderWidth:false,
borderColor:"#050747",
fontWeight:false,
textShadow:false,
},
{
title: "Footer",
backgroundColor: "#FFe5d9",
color: "black",
borderWidth: false,
borderColor: "#FFe5d9",
fontWeight: false,
textShadow:false,
}
]
